# Generated by Django 5.1.4 on 2024-12-16 04:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'verbose_name': 'Робот', 'verbose_name_plural': 'Роботы'},
        ),
        migrations.AlterField(
            model_name='robot',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message="Поле 'model' должно иметь от 1 до 2 латинских символов или чисел.", regex='^[A-Za-z0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='robot',
            name='version',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message="Поле 'version' должно иметь от 1 до 2 латинских символов или чисел.", regex='^[A-Za-z0-9]{2}$')]),
        ),
    ]
